version: '3.5'

services:
  reverse-proxy:
    image: traefik
    command: --log.level=DEBUG --api.insecure=true --providers.docker
    ports: 
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - divergen-network
  
  frontend:
    build:
      context: ./frontend/
      target: development-stage
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    networks:
      - divergen-network
    labels:
      - "traefik.http.routers.divergen-router.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.divergen-router.entrypoints.frontend.address=:3000"
      # - "traefik.port=3000"
      # - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      # - "traefik.http.routers.divergen-router.rule=Host(`local.divergen.cgds`)"
      

networks:
  divergen-network:
    name: divergen-network