version: '3.5'

services:
  frontend:
    image: gitlab.rc.uab.edu:4567/center-for-computational-genomics-and-data-science/development/divergen/frontend:vprod
    networks:
      divergen-network:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=divergen-network-prod"
        - "traefik.http.routers.divergen-frontend-prod-router.rule=Host(`prod`) && PathPrefix(`/divergen`)"
        - "traefik.http.routers.divergen-frontend-prod-router.service=divergen-prod-frontend"
        - "traefik.http.services.divergen-frontend-prod.loadbalancer.server.port=80"

  backend:
    image: gitlab.rc.uab.edu:4567/center-for-computational-genomics-and-data-science/development/divergen/backend:vprod
    networks:
      divergen-network:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=divergen-network-prod"
        - "traefik.http.routers.divergen-backend-prod-router.rule=Host(`prod`) && (`/api`)"
        - "traefik.http.divergen-backend-prod-router.service=backend-strip-prefix"
        - "traefik.http.middlewares.backend-strip-prefix.stripprefix.prefix=/api"
        - "traefik.services.divergen-backend-prod.loadbalancer.server.port=8000"

networks:
  divergen-network:
    name: divergen-network-prod
  traefik:
    name: traefik-public 
    external: true