version: '3.5'

services:
  reverse-proxy:
    image: traefik
    command: --log.level=DEBUG --api.insecure=true --providers.docker
    ports: 
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - divergen-network
  
  frontend:
    build:
      context: ./frontend/
      target: development-stage
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    networks:
      - divergen-network
    ports:
      - 3000:80
    labels:
      - "traefik.http.routers.divergen-router.service=frontend"
      - "traefik.http.routers.divergen-router.rule=Host(`localhost`)"

networks:
  divergen-network:
    name: divergen-network