version: '3.5'

services:
  reverse-proxy:
    image: traefik
    ports: 
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --log.level=DEBUG --api.insecure=true --entrypoints.web.address=:80
    networks:
      - divergen-network
  
  frontend:
    build:
      context: ./frontend/
      target: development-stage
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    networks:
      - divergen-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=divergen-network"
      - "traefik.http.routers.divergen-router.service=frontend"
      - "traefik.http.routers.divergen-router=Host(`localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

networks:
  divergen-network:
    name: divergen-network