version: '3.5'

services:
  frontend:
    image: gitlab.rc.uab.edu:4567/center-for-computational-genomics-and-data-science/development/rosalution/frontend:vprod
    networks:
      - rosalution-network
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.rosalution-frontend-prod-router.entrypoints=http"
        - "traefik.http.routers.rosalution-frontend-prod-router.rule=Host(`dev.cgds.uab.edu`) && PathPrefix(`/rosalution`)"
        - "traefik.http.routers.rosalution-frontend-prod-router.service=rosalution-frontend-prod-service"
        - "traefik.http.routers.rosalution-frontend-prod-router.middlewares=frontend-strip-prefix"
        - "traefik.http.middlewares.frontend-strip-prefix.stripprefix.prefixes=/rosalution"
        - "traefik.http.services.rosalution-frontend-prod-service.loadbalancer.server.port=80"

  backend:
    image: gitlab.rc.uab.edu:4567/center-for-computational-genomics-and-data-science/development/rosalution/backend:vprod
    networks:
      - rosalution-network
      - traefik
    environment:
      MONGODB_HOST: "rosalution-db"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.routers.rosalution-backend-prod-router.entrypoints=http"
        - "traefik.http.routers.rosalution-backend-prod-router.rule=Host(`dev.cgds.uab.edu`) && PathPrefix(`/rosalution/api`)"
        - "traefik.http.routers.rosalution-backend-prod-router.service=rosalution-backend-prod-service"
        - "traefik.http.routers.rosalution-backend-prod-router.middlewares=backend-strip-prefix"
        - "traefik.http.middlewares.backend-strip-prefix.stripprefix.prefixes=/rosalution/api"
        - "traefik.http.services.rosalution-backend-prod-service.loadbalancer.server.port=8000"

  rosalution-db:
    build:
      context: ./etc/fixtures/
      target: production-stage
      dockerfile: production.Dockerfile
    networks:
      - rosalution-network-prod
    environment:
      MONGO_INITDB_DATABASE: rosluation_db

networks:
  rosalution-network:
    name: rosalution-network-prod
  traefik:
    name: traefik-public
    external: true
