version: '3.5'

services:
  reverse-proxy:
    image: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.stream.address=:3000"
    ports: 
      - 80:80
      - 8080:8080
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - divergen-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=divergen-network"
  
  frontend:
    build:
      context: ./frontend/
      target: production-stage
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    networks:
      - divergen-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=divergen-network"
      - "traefik.http.routers.frontend-router.entrypoints=web,stream"
      - "traefik.http.routers.frontend-router.rule=Host(`local.divergen.cgds`)"
      - "traefik.http.routers.frontend-router.service=frontend-web-service"
      - "traefik.http.services.frontend-web-service.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend-router.service=frontend-stream-service"
      - "traefik.http.services.frontend-stream-service.loadbalancer.server.port=3000"

networks:
  divergen-network:
    name: divergen-network